name = "LaTeXCarpenter"
uuid = "d1239a56-209c-476f-afff-9040135ddd4e"
authors = ["Ruairidh South rsouth@princeton.edu"]
version = "0.1.1"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[weakdeps]
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"

[extensions]
CarpenterFixedEffects = "FixedEffectModels"
